# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            OMKAR PATHAK
tagline:          'Pythonista by &hearts;'
description:      'Software Developer by Profession, '
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
