# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            OMKAR PATHAK
tagline:          'Pythonista by &hearts;'
description:      'Software Developer by Profession, '
url:              http://temp.omkarpathak.in
baseurl:          /

author:
  name:           'Omkar Pathak'
  url:            https://twitter.com/omkarpathak27

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/OmkarPathak/omkarpathak.github.io
  
plugins:
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-avatar
    - jemoji
    - jekyll-mentions
