# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            OMKAR PATHAK
tagline:          ''
description:      'Software Developer by Profession, Pythonista by &hearts stuffed inside a compact, witty, artistic body'
url:              https://www.omkarpathak.in
baseurl:          

author:
  name:           'Omkar Pathak'
  url:            https://twitter.com/omkarpathak27

paginate:         6
paginate_path: 	  /blog/page:num/

version:          3.0.0

github:
  repo:           https://github.com/OmkarPathak/omkarpathak.github.io
  
plugins:
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-avatar
    - jemoji
    - jekyll-mentions
    - jekyll-paginate

twitter_username: omkarpathak27
github_username: OmkarPathak
linkedin_username: omkarpathak27
facebook_username: omkarpathak27
quora_username: Omkar-Pathak-18 
instagram_username: omkarpathak27

sketches:
  - public/img/sketches/2.jpg
  - public/img/sketches/1.jpg
  - public/img/sketches/5.jpg
  - public/img/sketches/6.jpg
  - public/img/sketches/4.jpg
  - public/img/sketches/3.jpg
  - public/img/sketches/7.jpg
  - public/img/sketches/8.jpg

photography:
  - public/img/photography/1.jpg
  - public/img/photography/18.png
  - public/img/photography/19.png
  - public/img/photography/20.png
  - public/img/photography/21.png
  - public/img/photography/22.png
  - public/img/photography/23.png
  - public/img/photography/24.png
  - public/img/photography/25.png
  - public/img/photography/26.png
  - public/img/photography/27.png
  - public/img/photography/28.png
  - public/img/photography/29.png
  - public/img/photography/30.png
  - public/img/photography/31.png
  - public/img/photography/32.jpeg
  - public/img/photography/33.jpeg
  - public/img/photography/34.jpeg
  - public/img/photography/35.jpeg
  - public/img/photography/36.jpeg
  - public/img/photography/37.jpg
  - public/img/photography/38.jpg
  - public/img/photography/39.jpg
  - public/img/photography/40.jpg
  - public/img/photography/41.jpg
  - public/img/photography/42.jpg
  - public/img/photography/43.jpg
  - public/img/photography/44.jpg
  - public/img/photography/45.jpg
  - public/img/photography/46.jpg
  - public/img/photography/47.jpg

photography_imgur:
  - https://i.imgur.com/Axmtv05.jpg
  - https://i.imgur.com/B8j7bvS.jpg
  - https://i.imgur.com/IoSjpmk.jpg
  - https://i.imgur.com/ugsTtid.jpg

illustrations:
  - public/img/illustrations/75_years.png
  - public/img/illustrations/friday_sigh.png
  - public/img/illustrations/ganpati.jpg
  - public/img/illustrations/ganpati_2.png
  - public/img/illustrations/ganpati_3.jpg
  - public/img/illustrations/ganpati_4.jpg
  - public/img/illustrations/hi.jpg
  - public/img/illustrations/hulk.jpg
  - public/img/illustrations/illsutrate.jpg
  - public/img/illustrations/illustrate_1.jpg
  - public/img/illustrations/illustrate_2.jpg
  - public/img/illustrations/iron_man.png
  - public/img/illustrations/kakashi.jpg
  - public/img/illustrations/kasa_kay_pune.jpg
  - public/img/illustrations/leonardo.png
  - public/img/illustrations/naruto.jpg
  - public/img/illustrations/oshin.jpg
  - public/img/illustrations/quote.jpg
  - public/img/illustrations/sheldon.png
  - public/img/illustrations/sketch.png